services:
  flask_app:
    build:
      context: ./flask_app  # Chỉ định đường dẫn đến thư mục chứa Dockerfile
      dockerfile: Dockerfile  # Tên Dockerfile, có thể bỏ qua nếu mặc định là 'Dockerfile'
    ports:
      - "5000:5000"  # Mở cổng để truy cập Flask app
    volumes:
      - ./flask_app:/app  # Đồng bộ mã nguồn từ host vào container để phát triển dễ dàng hơn
    environment:
      - FLASK_ENV=development  # Chạy Flask ở chế độ phát triển (tùy chọn)
    depends_on:
      - elasticsearch
      - kibana

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.0
    container_name: kibana
    ports:
      - "5601:5601"

volumes:
  esdata:
